create table tb_user (id int8 generated by default as identity, name varchar(255), email varchar(255), phone varchar(255), password varchar(255), primary key (id));
INSERT INTO tb_user(email) VALUES ('Maria Ducarmo','maria@gmail.com','5521999999999','12345678');

